vault:
  image: vault:0.8.3
  ports:
    - "8200:8200"
  volumes:
    - ./vault/config.hcl:/vault/config/vault.hcl
  environment:
    - VAULT_DEV_ROOT_TOKEN_ID=87e7784b-d598-44fe-8962-c7c345a11eed
    - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    - SKIP_SETCAP=true
    - disable_mlock=true
